title: Buddhadeb Mondal
description: Particle physicist working on the ATLAS experiment at CERN.
url: "https://bmondaliitb.github.io"
baseurl: ""
lang: en
timezone: Europe/Prague

markdown: kramdown
permalink: pretty

collections:
  research:
    output: true
    permalink: /research/:name/
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: research
    values:
      layout: research
  - scope:
      path: ""
      type: projects
    values:
      layout: project

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
